import{a as p,S as f,i as g}from"./assets/vendor-BYRgfgUc.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m=p.create({baseURL:"https://pixabay.com/api/",params:{key:"49094425-ee2da42b6a4a3e6a1c3a9f546",image_type:"photo",orientation:"horizontal",safesearch:!0}});function d(r){return m.get("",{params:{q:r}}).then(a=>{if(a.data.hits.length===0)throw new Error("No images found");return a.data})}document.querySelector(".gallery");document.querySelector(".loader");new f(".gallery a",{captionsData:"alt",captionDelay:250});function y({webformatURL:r,largeImageURL:a,tags:s,likes:i,views:e,comments:t,downloads:l}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${r}" alt="${s}" />
      </a>
      <ul class="gallery-sublist">
        <li class="gallery-subitem"><p class="sub-text">Likes</p><p class="sub-value">${i}</p></li>
        <li class="gallery-subitem"><p class="sub-text">Views</p><p class="sub-value">${e}</p></li>
        <li class="gallery-subitem"><p class="sub-text">Comments</p><p class="sub-value">${t}</p></li>
        <li class="gallery-subitem"><p class="sub-text">Downloads</p><p class="sub-value">${l}</p></li>
      </ul>
    </li>`}function h(r){return r.map(y).join("")}const o={form:document.querySelector("form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};let n;o.form.addEventListener("submit",b);function b(r){r.preventDefault(),o.gallery.innerHTML="",L();const a=r.target.elements.search.value.trim();if(!a){u("Please enter a search term!"),c();return}d(a).then(s=>{o.gallery.innerHTML=h(s.hits),n?n.refresh():n=new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}).catch(s=>{u("Sorry, there are no images matching <br> your search query. Please, try again!")}).finally(()=>{c()}),r.target.reset()}function c(){o.loader.style.display="none"}function L(){o.loader.style.display="block"}function u(r){g.warning({message:r,titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",iconUrl:"./img/octagon.svg",position:"topRight"})}
//# sourceMappingURL=index.js.map
